### PR TITLE
new Edit position endpoint and some code refactoring

### PR DESCRIPTION
**Pull request by Mortgy**

### CODE REVIEW

**Comment by Mortgy** [comment]
@ismailfer I think for some reason when I try to edit order twice, I can't get the order by Id, after restarting the project, I can get the order, if you may look into this part please :)

**Comment by ismailfer** [comment]
> @ismailfer I think for some reason when I try to edit order twice, I can't get the order by Id, after restarting the project, I can get the order, if you may look into this part please :)

hi Mohammed, are you looking up the order by ClientOrderID or by DukasOrderID ?

**Comment by Mortgy** [comment]
i check if any of them is provided, according to the provided one i go to look it up, but still i can't edit the same position more than once.

also i noticed some requests to history may fail, i'm not sure if i request too much data or not, i'll try to implement historical data though websocket

**Comment by ismailfer** [comment]
Ok

I have been busy lately with other projects. will check this out as soon as I can

By the way; you can chat with on Discord: ismailfer#0876

**Pull request merged**
